default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  pool: 5

development:
  <<: *default
  database: ysa_activity_development

test:
  <<: *default
  database: ysa_activity_test

production:
  <<: *default
  database: ysa_activity
  password: <%= ENV['YSA_ACTIVITY_DATABASE_PASSWORD'] %>
